# ==============================================================================
# Config.yml
# ------------------------------------------------------------------------------
#
# This is the main configuration file for the website. The 'theme' value should
# match the name of the folder in /themes that contains your theme files; if
# you've copied the default theme and given it a different name make sure to
# update the value here too.

baseURL: ""

title: "50X50: Stories of Visionary Artists from the Collection"
languageCode: "en-us"
theme: "sjma-5050-theme"
publishDir: site

footnoteReturnLinkContents: "↩"
metaDataFormat: "yaml"
GoogleAnalytics: ""

pluralizeListTitles: false
disableKinds:
  - "home"
  - "section"
  - "taxonomy"
  - "taxonomyTerm"

markup:
  goldmark:
    renderer:
      unsafe: true

# These values can be accessed in templates via .Site.Params
params:
  searchEnabled: true
  licenseIcons: true
  pageLabelDivider: ". "
  citationPageLocationDivider: ", "
  contributorByline: name-title # name | name-title | false
  displayBiblioShort: true
  imageDir: "img"
  tocType: full
  menuType: full
  prevPageButtonText: "Back"
  nextPageButtonText: "Next"
  entryPageSideBySideLayout: false
  entryPageObjectLinkText: "View in Collection"
  figureLabelLocation: on-top # below | on-top
  figureModal: true
  figureModalIcons: true
  figureZoom: true
  citationPopupStyle: text # text | icon
