version: 2.1

jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:trusty
    working_directory: ~/quire-starter
    steps:
      - checkout
      - run:
          name: Install NodeJS and NPM
          command: |
            set +e             
            touch $BASH_ENV  
            curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 10.16.3 && nvm alias default 10.16.3

            echo 'export NVM_DIR="$HOME/.nvm"' >> $BASH_ENV
            echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
            echo 'nvm use 10.16.3' >> $BASH_ENV
      - run:
          name: Add Netlify CLI
          command: |
            npm install -g netlify-cli
      - run:
          name: Install Prince XML
          command: |
            wget -q -O /tmp/prince.deb https://www.princexml.com/download/prince_12.5-1_ubuntu14.04_amd64.deb
            sudo dpkg -i /tmp/prince.deb
            rm /tmp/prince.deb
      - run:
          name: Install Pandoc
          command: |
            wget -q -O /tmp/pandoc.deb https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb
            sudo dpkg -i /tmp/pandoc.deb
            rm /tmp/pandoc.deb
      - add_ssh_keys:
          fingerprints:
            - "9b:ca:68:bb:73:d0:32:71:61:d5:44:19:c2:63:36:2e"
      - run:
          name: Clone and install quire-cli
          command: |
            git clone git@github.com:gettypubs/quire-cli.git ~/quire-cli
            cd ~/quire-cli/
            npm install -g
      - run:
          name: Remove key from config to add new one
          command: |
            > ~/.ssh/config
      - add_ssh_keys:
          fingerprints:
            - "90:fe:91:5e:bf:6d:4c:74:54:43:73:12:10:87:f1:76"
      - run:
          name: Add quire-starter-theme and move theme into themes folder
          command: |
            git clone git@github.com:gettypubs/quire-starter-theme.git ~/quire-starter-theme
            mv ~/quire-starter-theme/ ~/quire-starter/themes/
      - restore_cache:
          keys:
            - dependency-cache-{{ .Branch }}-{{ checksum "~/quire-starter/themes/quire-starter-theme/package-lock.json" }}
      - run:
          name: Install theme dependencies
          command: |
            cd ~/quire-starter/themes/quire-starter-theme/
            npm ci
      - run:
          name: Build Quire Site
          command: |
            cd ~/quire-starter
            quire build
      - run:
          name: Deploy to Netlify
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  netlify deploy --auth ${NETLIFY_AUTH_TOKEN} --dir ~/quire-starter/site --prod --site ${NETLIFY_SITE_ID} --message "CircleCI Production Deploy"
               else
                  netlify deploy --auth ${NETLIFY_AUTH_TOKEN} --dir ~/quire-starter/site --site ${NETLIFY_SITE_ID} --message "CircleCI Pull Request Deploy"
            fi
            echo ${CIRCLE_BRANCH}
      - run:
          name: Set Netlify Url
          command: |
            echo ${NETLIFY_AUTH_TOKEN}
            if [ "${CIRCLE_BRANCH}" != "master" ]; then
              netlify api getSite --data '{ "site_id": "${NETLIFY_SITE_ID}" }' --auth ${NETLIFY_AUTH_TOKEN} > site.json
            fi
            URL="$(node -pe 'JSON.parse(process.argv[1]).deploy_url' "$(cat test.json))"
            export NETLIFY_URL=URL
      - run:
          name: Send comment to Github
          command: |
            CI_PR_ID=`git log -n 1 | grep 'Merge pull request' | sed -e 's/.*#\([0-9]\+\).*/\1/'`
            curl -s -H "Authorization: token ${ACCESS_TOKEN}" -X POST -d '{"body": "\${NETLIFY_URL}\"}' "https://api.github.com/repos/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}/pull/${CI_PR_ID}/comments"
      - save_cache:
          paths:
            - ~/quire-starter/themes/quire-starter-theme/node_modules
            - ~/.npm
            - ~/.cache
          key: v3-dependency-cache-{{ checksum "~/quire-starter/themes/quire-starter-theme/package.json" }}
